clear
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select
mkdir -p ~/.config
starship preset plain-text-symbols -o ~/.config/starship.toml
echo '
[hostname]
ssh_only = false
trim_at = ""
format = "[$hostname]($style) in "
style = "bold bright-yellow"

[vagrant]
disabled = true
' >> ~/.config/starship.toml
eval "$(starship init zsh)"